### ISSUE TITLE
library racob used by win32ole makes plugin crash at random times

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-eventlog#11]
more info in https://github.com/enebo/racob/issues/1
this makes this plugin pretty much unusable

my environment: windows 7 64 bit, oracle jdk 8 64 bit

**Comment by ph** [comment]
@jsvd Can you add your Windows version to this issue?

**Comment by jsvd** [comment]
done

**Comment by jsvd** [comment]
Closed as per the alternativa implementation done in #21
