### ISSUE TITLE
Add charset or codec support

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-eventlog#3]
originally reported here:  https://github.com/elasticsearch/logstash/issues/2139

The eventlog input doesn't invoke @codec at all, so users can't change charset or other codec settings.

I don't know what fields from the Eventlog need to be decoded, though, maybe _just_ message? Maybe all of them?

This might be weird given the codec system acts, for inputs, as a deserialization, but with eventlog we already have an object and there's nothing to deserialize.

It's possible "codec" doesn't make sense for eventlogs, but instead we could provide a charset setting. Needs more research.

**Comment by dansmith65** [comment]
I'm not certain, but I suspect that [an issue I have with the amazon_es](https://github.com/awslabs/logstash-output-amazon_es/issues/17) output is related to this. Additionally, one of the few log entries that did get sent to amazon_es has what appear's to me to be an encoding issue:

Windows Event Viewer | Kibana via Amazon Elasticsearch
-------------------------------- | -----------------------------------------------
Impersonation Level:		Impersonation | Impersonation Level:		%%1833

My understanding is the EventLog is encoded in UTF-16LE but Logstash defaults to UTF-8. Here is a link to what I think is the eventlog library used by this project: https://github.com/djberg96/win32-eventlog/blob/bd236da2383979a83f25541e9be68a4f3b3234fe/lib/win32/eventlog.rb#L923
