### ISSUE TITLE
Windows eventlog events are being missed

### ISSUE THREAD

**Issue by jr5112** [logstash-plugins/logstash-input-eventlog#7]
Windows event log events are being missed.  I tracked this down to a bug introduced with the following code change:

https://github.com/logstash-plugins/logstash-input-eventlog/commit/ca7d25a2862d07acf5dcd164554944db78f372cb#diff-91442d979ce08aa384feb239514b1006

The change removed a begin rescue block that surrounded a call to the NextEvent method of a WMI query object.  Whenever NextEvent times out it causes an exception which now gets handled by the rescue statement for the run block.  There we have a one second sleep followed by a retry.  Execution resumes at the start of the run block which causes a new wmi query object to be created.  The NextEvent method then gets called against the new wmi query object instead of the original one.  Any events that occurred during the 1 second sleep not considered to be new events in relation to the new wmi query object, therefore NextEvent ignores them and waits for something else to come along.

The correct response to a timeout should be to do another iteration of the loop do block so that the original wmi query object gets reused.  Replacing the begin rescue block seems to produce the desired behavior, but I'm not exactly sure why it was removed so I don't know if that is the correct solution.  (Add to that the fact that I know very little about ruby.)  The description of the code change implies that the rescue statement was too broad.  In case whoever fixes this wants to add a more specific rescue statement, my debugging indicates that the time out exception is of class Java::OrgRacobCom::ComFailException.  I'd try to fix this myself, but as I said earlier I know little about ruby and don't want to risk making things worse.  Thanks for looking into this.

Jim

**Comment by jsvd** [comment]
fixed by cfa0c867773af7a5b39c2f9c8eef61ebdd5d7055
