### ISSUE TITLE
 no such file to load -- jruby-win32ole

### ISSUE THREAD

**Issue by silentdth** [logstash-plugins/logstash-input-eventlog#8]
Getting ` no such file to load -- jruby-win32ole` using Elasticsearch 1.4.1 and Logstash 1.4.2. See trace log below.

Here is my config file for Logstash:

    input {
          eventlog {
        type  => 'Win32-EventLog'
        logfile  => 'System'
      }
    }
    
    output { 
    	elasticsearch { host => localhost }
    }

Trace Log:

    Using milestone 2 input plugin 'eventlog'. This plugin should be stable, but if
    you see strange behavior, please let us know! For more information on plugin mil
    estones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
    LoadError: no such file to load -- jruby-win32ole
           require at org/jruby/RubyKernel.java:1085
           require at file:/C:/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-I
    NF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
           require at file:/C:/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-I
    NF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
           require at c:/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/po
    lyglot.rb:65
          register at c:/logstash/lib/logstash/inputs/eventlog.rb:36
      start_inputs at c:/logstash/lib/logstash/pipeline.rb:135
              each at org/jruby/RubyArray.java:1613
      start_inputs at c:/logstash/lib/logstash/pipeline.rb:134
               run at c:/logstash/lib/logstash/pipeline.rb:72
           execute at c:/logstash/lib/logstash/agent.rb:139
               run at c:\logstash\lib\logstash\runner.rb:168
              call at org/jruby/RubyProc.java:271
        initialize at c:/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/
    task.rb:12

Elasticsearch and Logstash were both installed using https://chocolatey.org on Windows 7 x64. 

I thought about installing `jruby` and then `jruby-win32ole` gem, but that wouldn't work with the custom jruby install path Logstash uses, right?

**Comment by ph** [comment]
The eventlog plugin was a contrib plugin and maybe there is something wrong with the contrib package installation from chocolatey, I did not investigate further.

You can try a few things:

1. Retry to install the contrib plugins following the automated or manual process at http://logstash.net/docs/1.4.2/contrib-plugins
2. Use NXLog to send JSON events to a tcp input, a lot of people on windows are using this kind of configuration with more success than eventlog.
3. We have just released logstash 1.5.0 rc4, you can try this version and install the eventlog plugin with the command `bin/plugin install logstash-input-event`

**Comment by silentdth** [comment]
Thanks.

1. Fails with this error:
    
    c:\logstash\bin>plugin install contrib --verbose
    -> Installing contrib...
    Trying https://github.com/null/contrib/archive/master.zip...
    Failed: IOException[Can't get https://github.com/null/contrib/archive/master.zip
     to C:\ProgramData\chocolatey\lib\elasticsearch\tools\elasticsearch-1.4.1\plugin
    s\contrib.zip]; nested: FileNotFoundException[https://github.com/null/contrib/ar
    chive/master.zip]; nested: FileNotFoundException[https://github.com/null/contrib
    /archive/master.zip];
    Failed to install contrib, reason: failed to download out of all possible locati
    ons..., use --verbose to get detailed information

2. I will try this if 3. fails.
3. Doing this now

**Comment by silentdth** [comment]
Using 1.5.0.rc4 fails with this error:

>C:\logstash-1.5.0.rc4>bin\plugin install logstash-input-event
>io/console not supported; tty will not be manipulated
>OpenSSL::X509::StoreError: setting default path failed: null
>  set_default_paths at org/jruby/ext/openssl/X509Store.java:165
>         SSLContext at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl/ssl-internal.rb:31
>                SSL at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl/ssl-internal.rb:22
>            OpenSSL at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl/ssl-internal.rb:21
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl/ssl-internal.rb:20
>               load at org/jruby/RubyKernel.java:1087
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/openss
>l/ssl-internal.rb:1
>            require at org/jruby/RubyKernel.java:1071
>            require at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/core_ext/kernel_require.rb:54
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/openss
>l/ssl-internal.rb:4
>               load at org/jruby/RubyKernel.java:1087
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl.rb:1
>            require at org/jruby/RubyKernel.java:1071
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl19/openssl.rb:21
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl/load.rb:1
>            require at org/jruby/RubyKernel.java:1071
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/jopens
>sl/load.rb:24
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/core_ext/kernel_require.rb:1
>            require at org/jruby/RubyKernel.java:1071
>            require at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/core_ext/kernel_require.rb:54
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/openss
>l.rb:1
>            require at org/jruby/RubyKernel.java:1071
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/core_ext/kernel_require.rb:1
>            require at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/core_ext/kernel_require.rb:54
>            require at org/jruby/RubyKernel.java:1071
>             (root) at C:/logstash-1.5.0.rc4/vendor/jruby/lib/ruby/shared/rubyge
>ms/security.rb:11
>             (root) at C:\logstash-1.5.0.rc4\lib\pluginmanager\main.rb:15

I will try method 2 now, NXLog.

**Comment by silentdth** [comment]
Interesting I'm getting some EventLog's coming in WITHOUT the plugin.

**Comment by wiibaa** [comment]
@silentdth can you please specify your java config: JAVA_HOME and  java version

**Comment by wiibaa** [comment]
Also please note that eventlog is not a contrib plugin. In 1.4.2 it was necessary to install the contrib to workaround the fact that the win32ole dependencies was moved from core gemspec to contrib gemspec with additional wmi plugins.

So in 1.5.0 eventlog plugin is prepackaged and should be usable out of the box

**Comment by silentdth** [comment]
@wiibaa sure

>C:\>echo %JAVA_HOME%
>C:\Program Files\Java\jre1.8.0_45

>C:\>java -version
j>ava version "1.8.0_45"
>Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
>Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by silentdth** [comment]
@wiibaa Thanks, that'd explain why it's working out of the box. Not for all events, but I'm sure that's configurable.

**Comment by wiibaa** [comment]
@silentdth is the SSL_CERT_FILE environment variable defined ? `echo %SSL_CERT_FILE%` ?

**Comment by silentdth** [comment]
@wiibaa Nice! That's it - my variable points to a nonexistant path (I recently uninstall ruby-1.9.3)

>C:\>echo %SSL_CERT_FILE%
>C:\ruby-1.9.3\cacert.pem
>
>C:\>cd ruby-1.9.3
>The system cannot find the path specified.
>
>C:\>

**Comment by silentdth** [comment]
Now I get this:

>C:\logstash-1.5.0.rc4>bin\plugin install logstash-input-event
>io/console not supported; tty will not be manipulated
>Validating logstash-input-event
>Plugin logstash-input-event does not exist
>ERROR: Installation aborted, verification failed for logstash-input-event

>C:\logstash-1.5.0.rc4>

Assuming the plugin name is wrong ,as it does not exist. I'll check it out at the logstash website.

**Comment by wiibaa** [comment]
@silentdth sounds almost good, did you try with `bin\plugin install logstash-input-eventlog`, seems @ph introduced a few confusion in this thread :wink:

**Comment by silentdth** [comment]
@wiibaa Great success!

>C:\logstash-1.5.0.rc4>bin\plugin install logstash-input-eventlog
>io/console not supported; tty will not be manipulated
>Validating logstash-input-eventlog
>Installing logstash-input-eventlog
>Installation successful

Thank you very much for your support. I'll close this issue now!

**Comment by ph** [comment]
Dang I've made a typo in the plugin name. 

@silenth if you encounter any Windows problems with 1.5.0 rc4 please report them!  We did more effort to make it work better on Windows but we still need more testing

**Comment by silentdth** [comment]
@ph Sure will let you know! I think I need some config as not all Event's are showing up - I'll keep going at it.
